main = "main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]

[deco]
app = ""
workspace = ""
bindings = []
enable_workflows = true

[[migrations]]
tag = "v1"
new_classes = [ "Workflow" ]

[durable_objects]
[[durable_objects.bindings]]
name = "DECO_CHAT_WORKFLOW_DO"
class_name = "Workflow"