#:schema node_modules/@deco/workers-runtime/config-schema.json
name = "deconfig"
main = "main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]
scope = "deco"

[assets]
directory = "./view-build"
binding = "ASSETS"

[[r2_buckets]]
binding = "DECONFIG_BLOBS"
bucket_name = "deconfig-blobs"

[deco]
workspace = "deco"
bindings = []
enable_workflows = true
local = false

[[migrations]]
tag = "v2"
new_sqlite_classes = [ "Blobs", "Branch" ]

[[migrations]]
tag = "v1"
new_classes = [ "Workflow" ]

[durable_objects]
[[durable_objects.bindings]]
name = "BLOBS"
class_name = "Blobs"

[[durable_objects.bindings]]
name = "BRANCH"
class_name = "Branch"

[[durable_objects.bindings]]
name = "DECO_CHAT_WORKFLOW_DO"
class_name = "Workflow"

[[rules]]
type = "Text"
globs = [ "**/*.sql" ]
fallthrough = true