#:schema node_modules/@deco/workers-runtime/config-schema.json
name = "deconfig"
main = "main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]
scope = "deco"

[assets]
directory = "./view-build"
binding = "ASSETS"

[[r2_buckets]]
binding = "DECONFIG_BLOBS"
bucket_name = "deconfig-blobs"

[deco]
workspace = "deco"
bindings = []
enable_workflows = true

[deco.integration]
description = "Deconfig is a tool for managing the configuration of your Deco workspace."
friendlyName = "Deconfig"
icon = "https://assets.decocache.com/mcp/24cfa17a-a0a8-40dc-9313-b4c3bdb63af6/deconfig_v1.png"

[[migrations]]
tag = "v1"
new_classes = [ "Workflow" ]
new_sqlite_classes = [ "Blobs", "Branch" ]

[durable_objects]
[[durable_objects.bindings]]
name = "BLOBS"
class_name = "Blobs"

[[durable_objects.bindings]]
name = "BRANCH"
class_name = "Branch"

[[durable_objects.bindings]]
name = "DECO_CHAT_WORKFLOW_DO"
class_name = "Workflow"

[[rules]]
type = "Text"
globs = [ "**/*.sql" ]
fallthrough = true