name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./apps/api
        run: |
          npm install --legacy-peer-deps

      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: "./apps/api"
          secrets: |
            SUPABASE_URL
            SUPABASE_SERVER_TOKEN
            TURSO_ORGANIZATION
            TURSO_GROUP_DATABASE_TOKEN
            TURSO_ADMIN_TOKEN
            CF_ACCOUNT_ID
            CF_API_TOKEN
            CF_DISPATCH_NAMESPACE
            CF_R2_ACCESS_KEY_ID
            CF_R2_SECRET_ACCESS_KEY
            RESEND_API_KEY
            OPENROUTER_API_KEY
            WALLET_API_KEY
            ANTHROPIC_API_KEY
            OPENAI_API_KEY
            DEEPSEEK_API_KEY
            GOOGLE_API_KEY
            OTEL_EXPORTER_OTLP_ENDPOINT
            OTEL_EXPORTER_OTLP_HEADERS
            AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY
            AWS_REGION
            DECO_CHAT_DATA_BUCKET_NAME
            STRIPE_SECRET_KEY
            STRIPE_WEBHOOK_SECRET
            CURRENCY_API_KEY
            ISSUER_JWT_SECRET
            LLMS_ENCRYPTION_KEY
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVER_TOKEN: ${{ secrets.SUPABASE_SERVER_TOKEN }}
          TURSO_ORGANIZATION: ${{ secrets.TURSO_ORGANIZATION }}
          TURSO_GROUP_DATABASE_TOKEN: ${{ secrets.TURSO_GROUP_DATABASE_TOKEN }}
          TURSO_ADMIN_TOKEN: ${{ secrets.TURSO_ADMIN_TOKEN }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_DISPATCH_NAMESPACE: "deco-chat-prod"
          CF_R2_ACCESS_KEY_ID: ${{ secrets.CF_R2_ACCESS_KEY_ID }}
          CF_R2_SECRET_ACCESS_KEY: ${{ secrets.CF_R2_SECRET_ACCESS_KEY }}
          WALLET_API_KEY: ${{ secrets.WALLET_API_KEY }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          WHATSAPP_ACCESS_TOKEN: ${{ secrets.WHATSAPP_ACCESS_TOKEN }}
          WHATSAPP_PHONE_NUMBER_ID: ${{ secrets.WHATSAPP_PHONE_NUMBER_ID }}
          WHATSAPP_API_VERSION: ${{ secrets.WHATSAPP_API_VERSION }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DECO_CHAT_DATA_BUCKET_NAME: ${{ secrets.DECO_CHAT_DATA_BUCKET_NAME }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
          CURRENCY_API_KEY: ${{ secrets.CURRENCY_API_KEY }}
          ISSUER_JWT_SECRET: ${{ secrets.ISSUER_JWT_SECRET }}
          LLMS_ENCRYPTION_KEY: ${{ secrets.LLMS_ENCRYPTION_KEY }}
