name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./apps/api
        run: |
          npm install --legacy-peer-deps

      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: "./apps/api"
          secrets: |
            SUPABASE_URL
            SUPABASE_SERVER_TOKEN
            TURSO_ORGANIZATION
            TURSO_GROUP_DATABASE_TOKEN
            TURSO_ADMIN_TOKEN
            CF_ACCOUNT_ID
            CF_API_TOKEN
            CF_DISPATCH_NAMESPACE
            RESEND_API_KEY
            OPENROUTER_API_KEY
            WALLET_API_KEY
            ANTHROPIC_API_KEY
            OPENAI_API_KEY
            DEEPSEEK_API_KEY
            GOOGLE_API_KEY
            OTEL_EXPORTER_OTLP_ENDPOINT
            OTEL_EXPORTER_OTLP_HEADERS
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVER_TOKEN: ${{ secrets.SUPABASE_SERVER_TOKEN }}
          TURSO_ORGANIZATION: ${{ secrets.TURSO_ORGANIZATION }}
          TURSO_GROUP_DATABASE_TOKEN: ${{ secrets.TURSO_GROUP_DATABASE_TOKEN }}
          TURSO_ADMIN_TOKEN: ${{ secrets.TURSO_ADMIN_TOKEN }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_DISPATCH_NAMESPACE: "deco-chat-prod"
          WALLET_API_KEY: ${{ secrets.WALLET_API_KEY }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
